### ISSUE TITLE
🎉 Launch day checklist 🎉

### ISSUE THREAD

**Issue by LizBaker** [newrelic/newrelic-quickstarts#258]
Related Doc  - `G-drive` `New Relic I/O: Launch Checklist`

It's time to launch Instant Observability 🎊
This is a place to track the tasks that need to get done for a successful launch

- [x] Update the install link in the dev site from staging to production
- [x] ~~Double check the video in the banner is correct~~
- [x] https://github.com/newrelic/developer-website/issues/1606
- [ ] Update the gatsby theme in all sites to bring in the new global header
- [x] Turn the nerdlet feature flags on to 100%
- [ ] Coordinate with `#help-website` to get [the redirects setup](https://github.com/newrelic/developer-website/issues/1599)
